---
title: "Average and top entry scores for the first 25 gameweeks"
author: "Rasmus Wiscostretford"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Suppose we are interested in tracking the average and top FPL scores by gameweek?

First we fetch the round information for a selection of gameweeks, say 1-25 for the 18/19 season, using the get_round_info function:

```{r, warning=F}

library(fplscrapR)

df <- get_round_info(round = 1:25, season = 18)
```

Next we use dplyr, tidyr and ggplot2 to transform and plot the data, showing the average and top entry progression by gameweek:

```{r, message=F,warning=F}
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r,warning=F,fig.width=7,fig.height=5}
df %>% 
  select(id,average_entry_score,highest_score) %>% # selecting the relevant columns
  gather("var","value",-id) %>% # transforming from wide to long format for ggplot
  ggplot() + # plotting using ggplot2
    geom_line(aes(x=id,y=value,colour=var),size=1) +
    theme_bw() +
    scale_x_continuous(breaks=1:25) +
    labs(x="Gameweek",y="Score",title="Average and top FPL entry scores by gameweek",caption=paste("Data from fplscrapR | ",Sys.Date(),sep=""))
```
