---
title: "Comparing historical FPL total season scores for Mesut Özil and Alexis Sanchez"
author: "Rasmus Wiscostretford"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Suppose we are interested in how the FPL histories of Mesut Özil and Alexis Sanchez compare?

First we fetch the player histories of those two players using get_player_hist, mobilising their playerids using get_player_id:

```{r, warning=F}

library(fplscrapR)

df <- get_player_hist(playerid=get_player_id(c("Mesut Özil","Alexis Sánchez"))$id)
```

Next we use dplyr and ggplot2 to transform and plot the data, showing the total FPL scores by season for the two players across their FPL careers:

```{r, message=F,warning=F}
library(dplyr)
library(ggplot2)
```

```{r,warning=F,fig.width=7,fig.height=5}
df %>% 
  select(playername,season_name,total_points) %>% # selecting the relevant columns
  ggplot() + # plotting using ggplot2
    geom_line(aes(x=season_name,y=total_points,group=playername,colour=playername),size=1) +
    theme_bw() +
    labs(x="Season",y="Total score",title="Historical FPL season scores by Özil and Sanchez",caption=paste("Data from fplscrapR | ",Sys.Date(),sep=""))
```
